[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = '''
[tox]
envlist = py35, py36, py37, py38, py39, py310

[testenv]
deps =
    opencv-python>=4.9.0.80
    numpy>=1.26.0
    fpdf2>=2.7.9
    numba>=0.59.0
    pdf2image>=1.17.0
    Pillow>=10.3.0
    pypdf>=4.0.0

commands =
    python src/PdfDarkMode/darkmode.py src/PdfDarkMode/test.pdf
'''